language: r
sudo: required
warnings_are_errors: true
notifications:
  email: false


before_install:
  ## PPA for Rcpp and some other packages
  - sudo add-apt-repository -y ppa:edd/misc
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_aptget libgsl0-dev gsl-bin
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"

install:
  - ./travis-tool.sh install_deps
  
script: ./travis-tool.sh run_tests

after_script:
  - ./travis-tool.sh dump_logs

env:
   global:
     - CRAN: http://cran.rstudio.com
     - R_BUILD_ARGS=" --compact-vignettes=gs+qpdf" 
     - R_CHECK_ARGS="--as-cran"
     - BOOTSTRAP_LATEX="1"
